server.port: 8081

debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example.securitypractice: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: debug
    org.springframework.security: debug

spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
 
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated

  devtools:
    livereload.enabled: true
    restart.enabled: true
